---
title: "A* Markdown"
author: "Adam Kurth"
date: "2023-11-13"
output: pdf_document
bibliography: cite.bib
---

```{r, warning=FALSE, message=FALSE, include=FALSE}
rm(list=ls())
library(tidyverse)
library(stats)
library(stats4)
library(gridExtra)
library(ggplot2)
library(ggpubr)
library(ggthemes)
library(ggfortify)
## custon functions
residuals_vs_fitted <- function(model) {
    ggplot(model, aes_string(x = ".fitted", y = ".resid")) +
        geom_point() +
        geom_hline(yintercept = 0, linetype = "dashed") +
        labs(x = "Fitted Values", y = "Residuals", title = "Residuals vs Fitted Values")
}

normal_qq <- function(model) {
    ggplot(model, aes(sample = .stdresid)) +
        stat_qq() +
        geom_abline(intercept = 0, slope = 1, linetype = "dashed") +
        labs(title = "Normal Q-Q Plot", x = "Theoretical Quantiles", y = "Sample Quantiles")
}

scale_location <- function(model) {
    ggplot(model, aes(.fitted, sqrt(abs(.stdresid)))) +
        geom_point() +
        geom_hline(yintercept = 0, linetype = "dashed") +
        labs(x = "Fitted Values", y = "Square Root of Standardized Residuals", title = "Scale-Location Plot")
}

leverage_plot <- function(model) {
    ggplot(model, aes(.hat, .stdresid)) +
        geom_point() +
        labs(x = "Leverage", y = "Standardized Residuals", title = "Residuals vs Leverage")
}
```

# Heading

```{r}


```